// One-time seed source for Supabase. Imported only by scripts/seed.ts.
// The runtime site reads from Supabase via lib/db/games.ts; this file
// is NOT imported by app/, components/, or lib/ — keep it that way.
import type { Game } from "../lib/types";

export const GAMES: Game[] = [
  {
    id: 1,
    slug: "pandemic",
    name: "Pandemic",
    icon: "🦠",
    ibg: "#E1F5EE",
    tc: "#0F6E56",
    tbg: "#E1F5EE",
    stem: "Biology & Epidemiology",
    subj: "Biology",
    type: "Cooperative",
    age: "8-12",
    time: "45–75 min",
    players: "2–4",
    bgg: 30549,
    wiki: "Pandemic_(board_game)",
    desc: "Discover how diseases spread, vaccines work, and the real science behind stopping global outbreaks.",
    detail:
      "Pandemic connects directly to epidemiology — the science of how diseases spread through populations. The game models real concepts like quarantine, contact tracing, and the race to develop vaccines. Players learn about infection rates, global health teamwork, and why handwashing literally destroys virus shells. Every mechanic reflects a real public health strategy.",
    concepts: [
      "Epidemiology",
      "Vaccines",
      "Quarantine",
      "Viruses",
      "Contact Tracing",
      "Public Health",
      "Immunology",
    ],
    roles: [
      { n: "Epidemiologist", d: "Tracks disease spread and models outbreak patterns." },
      { n: "Virologist", d: "Studies how viruses evolve and jump between species." },
      { n: "Public Health Expert", d: "Develops community-wide safety strategies." },
      { n: "Data Scientist", d: "Uses computers to predict where outbreaks happen next." },
    ],
    facts: [
      "The Black Death helped scientists first understand how diseases spread.",
      "COVID-19 put words like 'quarantine' and 'contact tracing' in everyday use.",
      "Flu viruses mutate so fast that a new vaccine is needed every single year.",
      "Viruses hijack your cells like tiny biological hackers — they're not truly alive.",
      "Pandemics shaped city design, school schedules, and even how we greet each other.",
      "Scientists who study outbreaks are called epidemiologists — real-life germ detectives!",
    ],
    tools: [
      "Vaccines train your immune system like a superhero boot camp.",
      "Handwashing with soap literally bursts the outer shell of many viruses.",
      "Masks catch the respiratory droplets that carry pathogens between people.",
      "Isolation and quarantine slow spread so hospitals don't get overwhelmed.",
      "Contact tracing identifies who's been exposed before symptoms appear.",
      "Global data sharing lets countries coordinate pandemic responses in real time.",
    ],
    exps: [
      {
        t: "Cough Cloud Test",
        s: [
          "Fill a spray bottle with water.",
          "Spray near paper without a barrier — measure how far droplets reach.",
          "Now hold a cloth (mask fabric) in front. Spray again.",
          "Compare wet spots. How much did the barrier reduce droplet spread?",
        ],
        w: "This models how respiratory droplets travel — and how masks physically block them. The same science drives real mask guidelines.",
      },
      {
        t: "The Banana Quarantine",
        s: [
          "Place one ripe banana in a sealed zip bag ('quarantine').",
          "Leave another banana out in open air.",
          "Observe both for 4–5 days.",
          "Which spoils faster, and why?",
        ],
        w: "Isolation limits exposure to mold spores and bacteria — paralleling how quarantine slows disease by reducing contact.",
      },
    ],
    books: [
      {
        t: "Plagues: The Microscopic Battlefield",
        a: "By Falynn Koch",
        d: "A graphic novel-style Science Comics book diving into viruses, bacteria, and how vaccines work.",
        ag: "Ages 9–13",
      },
      {
        t: "What Was the Plague?",
        a: "By Roberta Edwards",
        d: "An easy history of the bubonic plague that ravaged medieval Europe.",
        ag: "Ages 8–12",
      },
      {
        t: "I Survived the Black Death, 1349",
        a: "By Lauren Tarshis",
        d: "Historical fiction exploring life through one of history's deadliest pandemics.",
        ag: "Ages 8–12",
      },
    ],
  },
  {
    id: 2,
    slug: "terraforming-mars",
    name: "Terraforming Mars",
    icon: "🚀",
    ibg: "#EEEDFE",
    tc: "#534AB7",
    tbg: "#EEEDFE",
    stem: "Space Science & Engineering",
    subj: "Space",
    type: "Strategy",
    age: "12+",
    time: "120–180 min",
    players: "1–5",
    bgg: 167791,
    wiki: "Terraforming_Mars_(board_game)",
    desc: "Explore what it would really take to make Mars livable — from warming the planet to breathing its air.",
    detail:
      "Terraforming Mars is grounded in real planetary science. The game explores how greenhouse gases, giant mirrors, and microbial seeding could change a planet's climate over centuries. It covers atmospheric chemistry, Mars geology, and the engineering challenges of colonizing another world. Real scientists study every strategy shown in this game.",
    concepts: [
      "Planetary Science",
      "Atmospheric Chemistry",
      "Greenhouse Effect",
      "Gravity",
      "Terraforming",
      "Orbital Mechanics",
      "Astrobiology",
    ],
    roles: [
      { n: "Planetary Scientist", d: "Studies Mars's geology and potential for supporting life." },
      { n: "Aerospace Engineer", d: "Designs spacecraft and habitats for space environments." },
      { n: "Astrobiologist", d: "Investigates whether life can exist or be introduced on other planets." },
      { n: "Climate Scientist", d: "Models how greenhouse gases could warm Mars to habitable temperatures." },
    ],
    facts: [
      "Gravity on Mars is 1/3 of Earth's — you could dunk a basketball like an NBA pro!",
      "A Martian day is 24.6 hours — almost identical to Earth's.",
      "A Martian year lasts 687 Earth days — nearly two of our years.",
      "Mars has the largest volcano in the solar system: Olympus Mons, three times taller than Everest.",
      "Mars's atmosphere is 95% carbon dioxide — completely unbreathable.",
      "Average surface temperature on Mars is −80°F (−62°C).",
    ],
    tools: [
      "Greenhouse gases pumped into the atmosphere could slowly warm Mars over centuries.",
      "Giant orbital mirrors could reflect extra sunlight onto the Martian surface.",
      "Hardy microbes like algae could produce oxygen over thousands of years.",
      "Importing ammonia from asteroids could thicken and warm the thin atmosphere.",
      "Underground habitats protect humans from radiation while terraforming proceeds above.",
      "Each method is based on real research — actual terraforming would take thousands of years.",
    ],
    exps: [
      {
        t: "Simulated Martian Soil",
        s: [
          "Mix 1 cup sand, ¼ cup cornstarch, 1 tbsp cocoa powder — this mimics Martian regolith.",
          "Test how toy rover wheels move through it.",
          "Try planting small seeds. Do they grow?",
          "What does Martian soil lack that Earth soil has?",
        ],
        w: "Martian regolith lacks nutrients and helpful microbes. Scientists study how to grow food in it to support future Mars colonies.",
      },
      {
        t: "Water Recycling Challenge",
        s: [
          "Place a small cup of dirty water inside a large clear bowl.",
          "Cover the bowl tightly with plastic wrap, coin in center to create a dip.",
          "Set in sunlight and wait 45–60 minutes.",
          "Watch where clean water collects on the underside of the wrap.",
        ],
        w: "Solar distillation — the same process Martian bases would use to reclaim water from ice or soil. Sunlight evaporates water; it condenses as clean droplets.",
      },
    ],
    books: [
      { t: "Packing for Mars", a: "By Mary Roach", d: "A funny look at what it actually takes to live in space — eating, sleeping, and more.", ag: "Ages 14+" },
      { t: "Mars: You Decide How to Survive!", a: "By Hena Khan & David Borgenicht", d: "A choose-your-own-adventure nonfiction book about surviving on Mars.", ag: "Ages 10–14" },
      { t: "The Future of Humanity", a: "By Dr. Michio Kaku", d: "A world-famous physicist's big-picture look at colonizing other planets.", ag: "Ages 14+" },
    ],
  },
  {
    id: 3,
    slug: "wingspan",
    name: "Wingspan",
    icon: "🐦",
    ibg: "#EAF3DE",
    tc: "#3B6D11",
    tbg: "#EAF3DE",
    stem: "Ecology & Ornithology",
    subj: "Biology",
    type: "Card",
    age: "8-12",
    time: "40–70 min",
    players: "1–5",
    bgg: 266192,
    wiki: "Wingspan_(board_game)",
    desc: "Each card represents a real bird species. Discover ecology, habitats, and what it takes for wildlife to thrive.",
    detail:
      "Wingspan teaches ornithology and real ecology. Every bird card reflects accurate traits, diets, and habitats. Players learn about food webs, carrying capacity, biodiversity, and migration guided by Earth's magnetic field and stars. The game is used in real classrooms as a biology and conservation learning tool.",
    concepts: [
      "Ornithology",
      "Ecology",
      "Biodiversity",
      "Habitats",
      "Food Webs",
      "Migration",
      "Conservation",
    ],
    roles: [
      { n: "Ornithologist", d: "Studies bird behavior, anatomy, migration, and ecological roles." },
      { n: "Ecologist", d: "Examines how species interact with each other and their environment." },
      { n: "Conservation Biologist", d: "Works to protect endangered species and restore damaged habitats." },
      { n: "Citizen Scientist", d: "Records real bird sightings that help researchers track populations globally." },
    ],
    facts: [
      "Birds are endothermic — like mammals, they maintain their own body temperature.",
      "Most birds have hollow bones to reduce weight without sacrificing strength.",
      "Feathers serve multiple jobs: insulation, camouflage, flight, and attracting mates.",
      "Many birds can see ultraviolet light — the world looks completely different to them.",
      "Birds descended from theropod dinosaurs. Technically, birds ARE living dinosaurs!",
      "Some birds migrate thousands of miles guided by Earth's magnetic field and the stars.",
    ],
    tools: [
      "eBird and the Cornell Lab let anyone track birds and contribute to real science.",
      "GPS tagging lets scientists follow individual birds across entire continents.",
      "Habitat restoration by planting native plants helps birds find food and raise chicks.",
      "Breeding bird surveys count population changes to identify species needing protection.",
      "Biodiversity studies show that more varied ecosystems are healthier and more resilient.",
      "Climate modeling predicts how shifting temperatures will change bird migration routes.",
    ],
    exps: [
      {
        t: "Neighborhood Bird Count",
        s: [
          "Pick a 10-minute window at a local park or your backyard.",
          "Stay still and count every bird you see or hear.",
          "Download the free Merlin Bird ID app to identify what you spotted.",
          "Submit your count to eBird — your data gets added to a real global database!",
        ],
        w: "Real scientists use exactly this method — called point counts — to monitor bird populations worldwide. Your count contributes to genuine conservation research.",
      },
      {
        t: "Feather Function Test",
        s: [
          "Find a feather outdoors or buy at a craft store.",
          "Cut a strip of regular paper the same length.",
          "Slowly drip water over each from a spoon.",
          "Compare how water behaves on each surface. Why?",
        ],
        w: "Feathers have microscopic hooks (like velcro) and a natural oil coating that makes them waterproof — critical for ducks and diving birds.",
      },
    ],
    books: [
      { t: "All About Birds: Northeast", a: "By The Cornell Lab of Ornithology", d: "A regional bird guide with descriptions, range maps, and spotting tips.", ag: "Ages 10+" },
      { t: "Bird Songs: 250 North American Birds in Song", a: "By Les Beletsky", d: "Combines illustrations with 250 authentic bird calls to bring birds to life.", ag: "Ages 12+" },
      { t: "Eyewitness: Bird", a: "By David Burnie", d: "A visually rich overview of bird anatomy, behavior, migration, and diversity.", ag: "Ages 8–12" },
    ],
  },
  {
    id: 4,
    slug: "clue",
    name: "Clue",
    icon: "🔍",
    ibg: "#FAECE7",
    tc: "#993C1D",
    tbg: "#FAECE7",
    stem: "Forensics & Logic",
    subj: "Forensics",
    type: "Strategy",
    age: "8-12",
    time: "45–75 min",
    players: "2–6",
    bgg: 1294,
    wiki: "Cluedo",
    desc: "Use deduction and evidence just like real forensic scientists to solve mysteries step by step.",
    detail:
      "Clue mirrors the scientific method perfectly — form a hypothesis, gather evidence, eliminate possibilities, and draw conclusions. Real forensic scientists use fingerprints, DNA, fiber analysis, and handwriting examination with the exact same logical process players use every turn. The game builds critical thinking skills that transfer to real scientific inquiry.",
    concepts: [
      "Forensic Science",
      "Deductive Reasoning",
      "DNA Analysis",
      "Logic",
      "Evidence",
      "Pattern Recognition",
    ],
    roles: [
      { n: "Forensic Scientist", d: "Analyzes physical evidence using chemistry and biology." },
      { n: "Crime Scene Investigator", d: "Collects and documents physical evidence without contaminating it." },
      { n: "Behavioral Analyst", d: "Studies psychology to understand suspects and predict behavior." },
      { n: "Toxicologist", d: "Identifies poisons, drugs, and chemicals involved in crimes." },
    ],
    facts: [
      "Forensic science means using scientific methods to answer legal questions.",
      "Fingerprints are unique to every person — even identical twins have different prints!",
      "DNA evidence can link a person to a crime scene from just a single hair or skin cell.",
      "Handwriting analysis helps investigators identify forged documents and signatures.",
      "Footprints, tire tracks, hair, and fibers can all be critical crime scene evidence.",
      "Alan Turing cracked the Enigma code using the same logic as deductive elimination in Clue.",
    ],
    tools: [
      "Fingerprint dusting uses fine powder to reveal prints left by skin oils on surfaces.",
      "DNA gel electrophoresis separates genetic material to create a genetic fingerprint.",
      "Gas chromatography identifies unknown chemical substances found at crime scenes.",
      "Luminol spray makes blood traces glow under UV light even after cleaning.",
      "Ballistics experts match bullets to specific guns using unique barrel markings.",
      "Digital forensics recovers deleted files and messages from electronic devices.",
    ],
    exps: [
      {
        t: "Fingerprint Detective",
        s: [
          "Scribble a graphite patch with a soft pencil on paper.",
          "Rub your fingertip in it for 10–15 seconds.",
          "Press fingertip gently onto clear tape, stick tape on white paper.",
          "Compare your print with others. Find loops, whorls, and arches!",
        ],
        w: "This is exactly how forensic scientists collect latent fingerprints. Graphite sticks to skin oils, making the ridge patterns visible — the same method used in real investigations.",
      },
      {
        t: "Secret Code Maker",
        s: [
          "Create a simple cipher: assign numbers or symbols to each letter.",
          "Write a message in your code.",
          "Give it to a friend to crack without the key.",
          "Try to crack theirs in return!",
        ],
        w: "Code-breaking uses pattern recognition and deductive logic — the exact same mental tools real cryptographers and detectives use to decode hidden messages.",
      },
    ],
    books: [
      { t: "Spy", a: "By Richard Platt", d: "A visual guide to espionage tools, disguises, and spy techniques throughout history.", ag: "Ages 8–12" },
      { t: "Crime and Detection", a: "By Brian Lane", d: "A DK Eyewitness book on how real investigators solve mysteries, from fingerprinting to lie detectors.", ag: "Ages 8–12" },
      { t: "American Sherlock", a: "By Kate Winkler Dawson", d: "The story of Edward Oscar Heinrich, one of the first modern forensic scientists.", ag: "Ages 15+" },
    ],
  },
  {
    id: 5,
    slug: "catan",
    name: "Catan",
    icon: "🏝",
    ibg: "#FAEEDA",
    tc: "#BA7517",
    tbg: "#FAEEDA",
    stem: "Geography & Resource Science",
    subj: "Geography",
    type: "Strategy",
    age: "8-12",
    time: "60–120 min",
    players: "3–4",
    bgg: 13,
    wiki: "Catan_(board_game)",
    desc: "Trade resources, build cities, and explore how geography and economics shaped human settlements.",
    detail:
      "Catan models real geographic and economic concepts. Resource scarcity, settlement patterns, and infrastructure development mirror how human civilizations have grown. The hexagonal tiles map landscapes just as geographers do. The game reflects probability, trade economics, and the real environmental impact of expansion.",
    concepts: [
      "Geography",
      "Resource Management",
      "Economics",
      "Probability",
      "Sustainability",
      "Settlement History",
      "Infrastructure",
    ],
    roles: [
      { n: "Urban Planner", d: "Designs communities, roads, and settlements." },
      { n: "Economist", d: "Studies how resources are produced, distributed, and traded." },
      { n: "Environmental Scientist", d: "Examines how resource extraction affects land and ecosystems." },
      { n: "Geographer", d: "Maps how physical features determine where people settle and prosper." },
    ],
    facts: [
      "Ancient settlements clustered near rivers, coasts, and fertile valleys for resources.",
      "Wood and brick were the earliest building materials used by virtually every civilization.",
      "Early human communities bartered goods long before coins were invented.",
      "The probability of rolling each number in Catan is pure mathematics — combinations of two dice.",
      "Ore (metal) transformed civilizations by enabling stronger tools and construction.",
      "Modern cities still follow resource logic: ports near water, farms near fertile soil.",
    ],
    tools: [
      "GIS maps resources and helps planners decide where to build infrastructure.",
      "Probability modeling helps economists predict supply and demand for key resources.",
      "Environmental impact assessments measure how development affects local ecosystems.",
      "Trade route analysis shows how geography shaped which cities became powerful.",
      "Sustainable resource management studies how to use nature without depleting it.",
      "Archaeological records show exactly how ancient settlements expanded — just like in Catan.",
    ],
    exps: [
      {
        t: "Build Your Own Resource Map",
        s: [
          "Draw a grid of hexagons on paper (trace a hex template).",
          "Assign each hex a resource: wood, stone, wheat, clay, or pasture.",
          "Add numbers 2–12 weighted by probability.",
          "Pick your ideal starting settlement and explain your reasoning!",
        ],
        w: "This shows how geography and probability affect settlement planning — the same factors that drove ancient humans to settle near rivers and fertile valleys.",
      },
      {
        t: "Erosion in Action",
        s: [
          "Fill a tray with moist sand and soil.",
          "Build a mini village on a slope using small rocks or toy houses.",
          "Slowly pour water from the high end.",
          "Observe what happens to your village and the landscape.",
        ],
        w: "Land erosion explains why ancient cities were built on high ground or away from floodplains — the same geographic logic as choosing settlements in Catan.",
      },
    ],
    books: [
      { t: "Statues of Easter Island", a: "By Elizabeth Raum", d: "Explores the resource challenges and mysteries of Easter Island — a real-world Catan story.", ag: "Ages 8–11" },
      { t: "Eyewitness: Vikings", a: "By Susan M. Margeson", d: "Dives into Viking settlers and traders who expanded into new lands — just like in Catan.", ag: "Ages 9–12" },
      { t: "Community Resources", a: "By Dwayne Hicks", d: "Introduces shared resources — water, food, energy, land — and how communities manage them.", ag: "Ages 7–10" },
    ],
  },
  {
    id: 6,
    slug: "finspan",
    name: "Finspan",
    icon: "🐠",
    ibg: "#E6F1FB",
    tc: "#185FA5",
    tbg: "#E6F1FB",
    stem: "Marine Biology & Evolution",
    subj: "Biology",
    type: "Card",
    age: "8-12",
    time: "45–75 min",
    players: "1–4",
    bgg: 436126,
    wiki: "Finspan",
    desc: "Design fish species and discover how real adaptations — fins, scales, and colors — help creatures survive.",
    detail:
      "Finspan models real evolutionary biology. Each fin shape and trait connects to actual fish adaptations shaped by natural selection. Players learn about bioluminescence, hydrodynamics, camouflage, and how the lateral line gives fish extraordinary sensory abilities beyond human capability.",
    concepts: [
      "Evolution",
      "Adaptation",
      "Marine Biology",
      "Natural Selection",
      "Bioluminescence",
      "Hydrodynamics",
      "Sensory Biology",
    ],
    roles: [
      { n: "Marine Biologist", d: "Studies ocean creatures — their anatomy, behavior, and ecosystems." },
      { n: "Evolutionary Biologist", d: "Investigates how species change over generations in response to their environment." },
      { n: "Ichthyologist", d: "Specializes in the study of fish species and their biology." },
      { n: "Biomechanical Engineer", d: "Studies how animals move to improve robots and vehicles." },
    ],
    facts: [
      "The black marlin is the fastest fish in the ocean, swimming over 80 mph!",
      "Some fish glow in the dark using bioluminescence to attract prey or find mates.",
      "A fish's lateral line detects water movement with incredible precision — underwater radar.",
      "Many fish change sex as they grow — determined by social conditions, not birth.",
      "Fin shapes range from paddles to fans to blades — each specialized for different movement.",
      "Sharks can detect electrical fields produced by other animals' muscles.",
    ],
    tools: [
      "Hydrodynamic modeling tests how different body shapes reduce drag in water.",
      "CT scanning lets scientists see fish anatomy in 3D without any dissection.",
      "Underwater cameras document deep-sea creatures never seen before.",
      "Genetic sequencing reveals how fish species are related and how they evolved.",
      "Sonar technology inspired by fish lateral lines is used in submarines today.",
      "Biofluorescence research shows many fish glow in ways invisible to the human eye.",
    ],
    exps: [
      {
        t: "Fin Shape Speed Test",
        s: [
          "Cut fin shapes from cardstock: long & narrow, short & wide, rounded.",
          "Tape each fin to a craft stick.",
          "Drag each shape through a container of water.",
          "Which shape moves most easily? Which creates the most resistance?",
        ],
        w: "This tests how fin shape affects drag — the same hydrodynamic principles engineers use to design submarines, performance swimsuits, and airplane wings.",
      },
      {
        t: "Lateral Line Detection",
        s: [
          "Fill a bowl with water and let it become completely still.",
          "Gently float a small toy or cork on the surface.",
          "Tap the side of the bowl in different spots without touching the water.",
          "Watch how vibrations spread across the surface.",
        ],
        w: "Fish sense these same vibrations through their lateral line even in total darkness — helping them find prey, avoid predators, and school together with precision.",
      },
    ],
    books: [
      { t: "Fish", a: "By Steve Parker", d: "Explores fish anatomy, behavior, and habitats around the world.", ag: "Ages 8–11" },
      { t: "Pond and River", a: "By Steve Parker", d: "A DK Eyewitness look at freshwater ecosystems, food chains, and aquatic animals.", ag: "Ages 8–12" },
      { t: "Fish", a: "By Elizabeth Schleichert", d: "Beautiful photos and accessible explanations of fish types and habitats.", ag: "Ages 7–10" },
    ],
  },
  {
    id: 7,
    slug: "the-crew",
    name: "The Crew",
    icon: "🌌",
    ibg: "#EEEDFE",
    tc: "#534AB7",
    tbg: "#EEEDFE",
    stem: "Space Science & Communication",
    subj: "Space",
    type: "Cooperative",
    age: "8-12",
    time: "20–30 min",
    players: "3–5",
    bgg: 284083,
    wiki: "The_Crew:_The_Quest_for_Planet_Nine",
    desc: "Work like real astronauts — coordinate through silent signals to complete a deep space mission.",
    detail:
      "The Crew reflects real space mission dynamics: communication under constraint, mission roles, and coordinating under pressure. Planet Nine may actually exist based on gravitational anomalies in the outer solar system. Deep-space communication genuinely involves long delays — just as the game simulates with its communication rules.",
    concepts: [
      "Space Exploration",
      "Gravity",
      "Teamwork",
      "Communication",
      "Solar System",
      "Orbital Mechanics",
      "Signal Delay",
    ],
    roles: [
      { n: "Mission Commander", d: "Leads the crew and ensures mission objectives are met." },
      { n: "Flight Engineer", d: "Oversees life support, propulsion, and spacecraft mechanics." },
      { n: "Communications Officer", d: "Manages signals between spacecraft and mission control." },
      { n: "Navigation Officer", d: "Calculates orbital paths through deep space." },
    ],
    facts: [
      "Planet Nine might actually exist — inferred from gravitational effects on outer solar system objects.",
      "Neptune was discovered by mathematical prediction before any telescope confirmed it in 1846.",
      "The Kuiper Belt beyond Neptune is packed with icy objects and dwarf planets.",
      "Signals from Voyager 1 take over 20 hours to reach Earth — one way!",
      "Astronauts rely on non-verbal communication protocols — just like players in The Crew.",
      "The International Space Station travels at 17,500 mph, completing 16 orbits every day.",
    ],
    tools: [
      "Radio telescopes detect gravitational signals from objects too distant to see directly.",
      "Mathematical orbital mechanics predicted Planet Nine before any observation.",
      "Non-verbal protocols allow crew coordination in high-noise environments.",
      "Mission control continuously monitors telemetry from spacecraft millions of miles away.",
      "Gravity assist maneuvers use planetary gravity to slingshot craft to distant destinations.",
      "Spectrometry identifies chemical compositions of planets from their light signature.",
    ],
    exps: [
      {
        t: "Hidden Planet Gravity Model",
        s: [
          "Stretch a sheet or towel across a bowl or frame.",
          "Place a heavy ball (representing the Sun) in the center.",
          "Roll marbles across the sheet — watch how they curve.",
          "Add a second heavy object hidden under the sheet. Watch orbits change!",
        ],
        w: "Scientists inferred Planet Nine's existence by observing how known outer solar system objects deviate from expected paths — gravity revealing what eyes cannot see.",
      },
      {
        t: "Space Team Silent Protocol",
        s: [
          "Form a team of 3–4 people.",
          "Assign mission roles: pilot, engineer, communications, science.",
          "Create hand signals for key commands.",
          "Complete a simple puzzle using ONLY your signal system — no talking!",
        ],
        w: "Mission crews train for communication failures. This builds the same coordination and non-verbal communication that astronauts practice for spacewalks.",
      },
    ],
    books: [
      { t: "The Sun and Our Solar System", a: "By Jen Green", d: "A beautifully illustrated guide to the sun, planets, solar flares, and planetary orbits.", ag: "Ages 8–11" },
      { t: "Saving the Solar System", a: "By Nel Yomtov", d: "A future-focused look at Mars missions, asteroid mining, and the search for life on exoplanets.", ag: "Ages 9–12" },
      { t: "Eyewitness: Universe", a: "By Robin Kerrod", d: "Stunning visuals about stars, galaxies, black holes, and the structure of the universe.", ag: "Ages 8–12" },
    ],
  },
  {
    id: 8,
    slug: "castle-panic",
    name: "Castle Panic",
    icon: "🏰",
    ibg: "#FAEEDA",
    tc: "#BA7517",
    tbg: "#FAEEDA",
    stem: "Engineering & Physics",
    subj: "Engineering",
    type: "Cooperative",
    age: "8-12",
    time: "45–60 min",
    players: "1–6",
    bgg: 43443,
    wiki: "Castle_Panic",
    desc: "Defend your castle and discover the real engineering behind medieval fortifications — walls, towers, and moats.",
    detail:
      "Real castles were engineering marvels built using physics and mathematics. Stone walls 6–10 feet thick, round towers to deflect projectiles, strategic arrow slits — all designed to absorb, redirect, and resist forces. Castle Panic lets players experience defensive engineering principles firsthand through every card they play.",
    concepts: [
      "Structural Engineering",
      "Physics of Forces",
      "Architecture",
      "Compression",
      "Medieval History",
      "Defense Design",
      "Geometry",
    ],
    roles: [
      { n: "Structural Engineer", d: "Designs buildings and walls to withstand forces without collapsing." },
      { n: "Materials Scientist", d: "Studies which building materials are strongest and most durable." },
      { n: "Military Architect", d: "Historically designed fortifications balancing defense and resources." },
      { n: "Physicist", d: "Calculates forces of tension, compression, gravity, and projectile motion." },
    ],
    facts: [
      "Real castle walls were 6–10 feet thick — wide enough to walk along the top!",
      "Round towers deflect projectiles better than square ones.",
      "Moats slowed attackers and prevented tunneling under castle walls.",
      "Arrow slits were angled to let archers aim wide angles while staying protected.",
      "Portcullises — heavy iron gates — could seal castle entrances in seconds.",
      "Medieval builders used mathematical ratios like the golden ratio to design stable structures.",
    ],
    tools: [
      "Compression and tension analysis determines how forces distribute through structures.",
      "Arch design redirects weight to the sides rather than straight down — used in doorways.",
      "Buttresses transfer wall weight outward to prevent collapse.",
      "Site analysis chooses defensible locations: hilltops, island positions, cliff edges.",
      "Material testing identifies which stones and mortars are strongest and most weatherproof.",
      "Projectile physics calculates the force and arc of trebuchet and catapult ammunition.",
    ],
    exps: [
      {
        t: "Mini Wall Strength Test",
        s: [
          "Build 3 small walls from sugar cubes: straight, curved, and triangle-based.",
          "Stack coins slowly on each wall.",
          "Record how many coins each holds before collapsing.",
          "Try adding a little white glue between cubes. Retest!",
        ],
        w: "This tests how shape and binding agents affect structural strength — exactly what medieval engineers calculated when choosing wall designs.",
      },
      {
        t: "Arrow Slit Target Game",
        s: [
          "Cut narrow vertical slits in one side of a cardboard box.",
          "Place a paper target inside the box.",
          "Try to shoot paper balls through the slits from different angles.",
          "Move further away — how does distance affect your accuracy?",
        ],
        w: "Arrow slits were cut at precise angles to maximize archer field of fire while keeping them protected. Physics and geometry, working together.",
      },
    ],
    books: [
      { t: "National Geographic Kids Everything Castles", a: "By Crispin Boyer", d: "Stunning photos and facts about real castles, moats, dungeons, and daily medieval life.", ag: "Ages 8–11" },
      { t: "Castle", a: "By David Macaulay", d: "Detailed illustrated book showing step-by-step medieval castle construction with technical drawings.", ag: "Ages 9–12" },
      { t: "Knight", a: "By Christopher Gravett", d: "Covers the life of a medieval knight — training, armor, weapons, and battlefield tactics.", ag: "Ages 8–12" },
    ],
  },
  {
    id: 9,
    slug: "ticket-to-ride",
    name: "Ticket to Ride",
    icon: "🚂",
    ibg: "#E1F5EE",
    tc: "#0F6E56",
    tbg: "#E1F5EE",
    stem: "Geography & Transportation",
    subj: "Geography",
    type: "Strategy",
    age: "5-8",
    time: "45–75 min",
    players: "2–5",
    bgg: 9209,
    wiki: "Ticket_to_Ride_(board_game)",
    desc: "Build rail routes across America and learn how transportation networks shaped cities and history.",
    detail:
      "Ticket to Ride models real geography and network science. The transcontinental railroad transformed America in 1869 — and the game shows why route planning matters. Players explore friction, traction, probability of route blockage, and how transportation networks build or break communities over time.",
    concepts: [
      "Geography",
      "Transportation Networks",
      "Friction",
      "Railroad History",
      "Route Planning",
      "Network Science",
      "Probability",
    ],
    roles: [
      { n: "Civil Engineer", d: "Designs and plans roads, bridges, railways, and major infrastructure." },
      { n: "Urban Planner", d: "Decides where transportation links go and how they shape city growth." },
      { n: "Transportation Economist", d: "Studies how connectivity between cities affects trade and prosperity." },
      { n: "Network Scientist", d: "Maps and analyzes how systems — rail, internet, power grids — interconnect." },
    ],
    facts: [
      "The first US transcontinental railroad was completed on May 10, 1869 at Promontory Summit, Utah.",
      "Trains move using friction and traction — the grip between steel wheels and steel rails.",
      "Railroads let people travel cross-country in days instead of the months it took by wagon.",
      "Networks — train lines, the internet, airline routes — all follow the same mathematical structure.",
      "Train stations were deliberately built near city centers to drive economic growth.",
      "Blocked rail routes caused towns to shrink or disappear entirely — just like in the game.",
    ],
    tools: [
      "Friction testing measures how surface materials affect wheel grip and stopping distance.",
      "Network analysis maps the most efficient connections between cities or nodes.",
      "GIS plans the most practical routes through physical terrain.",
      "Speed-time-distance calculations determine train schedules and fuel efficiency.",
      "Route optimization algorithms — the same ones in GPS — find shortest paths through networks.",
      "Historical analysis shows how rail expansion changed American settlement patterns westward.",
    ],
    exps: [
      {
        t: "Train Traction Test",
        s: [
          "Set up a toy car at the top of a ramp made from a book.",
          "Release it on different surfaces: carpet, cardboard, tile, sandpaper.",
          "Measure how far it travels past the ramp on each surface.",
          "Rank surfaces from highest to lowest friction.",
        ],
        w: "This demonstrates how friction affects train movement — too much wastes energy, too little and wheels spin. Rail engineers optimize this exact balance on every track.",
      },
      {
        t: "Network Route Challenge",
        s: [
          "Place 8 coins on paper as 'cities.'",
          "Connect them with lines trying to link all cities using the fewest lines.",
          "Find the shortest route that visits every city exactly once.",
          "Compare solutions with a partner.",
        ],
        w: "This is the classic 'Traveling Salesman Problem' — a real mathematical puzzle that powers GPS navigation, delivery routes, and railroad scheduling.",
      },
    ],
    books: [
      { t: "Train", a: "By John Coiley", d: "Explores the rich history of trains from early steam locomotives to modern rail.", ag: "Ages 7–10" },
      { t: "Trains: Railways, Tunnels, Signals, Diesel, Steam", a: "By Michael Harris & Steve Parker", d: "A comprehensive look at how trains work and how railroads shape our world.", ag: "Ages 8–12" },
      { t: "All Aboard! How Trains Work", a: "By Jennifer Prior", d: "Beginner-friendly nonfiction breaking down engines, tracks, and conductors.", ag: "Ages 6–9" },
    ],
  },
  {
    id: 10,
    slug: "codenames",
    name: "Codenames",
    icon: "🕵️",
    ibg: "#FAECE7",
    tc: "#993C1D",
    tbg: "#FAECE7",
    stem: "Cryptography & Logic",
    subj: "Forensics",
    type: "Word",
    age: "8-12",
    time: "15–30 min",
    players: "4–8",
    bgg: 178900,
    wiki: "Codenames_(board_game)",
    desc: "Think like a spy! Discover how real codes, ciphers, and secret communications have shaped history.",
    detail:
      "Codenames mirrors real cryptography and intelligence work. Throughout history, spies have used ciphers, invisible ink, and coded signals. The game develops core intelligence analyst skills: word association, logical deduction, pattern recognition, and communicating under uncertainty — all used in real espionage.",
    concepts: [
      "Cryptography",
      "Logic",
      "Espionage",
      "Communication",
      "Pattern Recognition",
      "Code-Breaking",
      "Psychology",
    ],
    roles: [
      { n: "Cryptographer", d: "Designs and breaks codes and ciphers to protect or reveal messages." },
      { n: "Intelligence Analyst", d: "Interprets coded information and connects clues to larger patterns." },
      { n: "Linguistic Scientist", d: "Studies how words carry meaning and relate to each other." },
      { n: "Behavioral Psychologist", d: "Understands how people communicate and make decisions under pressure." },
    ],
    facts: [
      "Julius Caesar used a simple letter-shift cipher over 2,000 years ago — it still bears his name.",
      "The Nazi Enigma machine created codes so complex they took genius mathematicians to crack.",
      "Alan Turing broke Enigma using logic and early computing — saving millions of lives in WWII.",
      "Spies have used invisible ink, hollow coins, and disguised radios to pass secret messages.",
      "Modern internet encryption (https) uses mathematics millions of times more complex than Caesar's cipher.",
      "The Navajo Code Talkers in WWII created an unbreakable code using their native language.",
    ],
    tools: [
      "Substitution ciphers replace each letter with another symbol, number, or letter.",
      "Public key cryptography lets two people communicate secretly without ever sharing a key.",
      "Steganography hides messages inside images, audio files, or other innocent-looking content.",
      "Hash functions create digital fingerprints used to verify files haven't been tampered with.",
      "Frequency analysis decodes simple ciphers by counting how often each symbol appears.",
      "Quantum cryptography uses physics principles to create theoretically unbreakable communication.",
    ],
    exps: [
      {
        t: "Invisible Ink Messaging",
        s: [
          "Dip a cotton swab in fresh lemon juice.",
          "Write a secret message on white paper.",
          "Let it dry completely — it becomes invisible.",
          "Hold the paper near a warm lamp bulb for 30–60 seconds. What appears?",
        ],
        w: "Lemon juice oxidizes when heated, turning brown. This is exactly the chemistry real historical spies used — and it works with orange juice or milk too!",
      },
      {
        t: "Frequency Analysis Challenge",
        s: [
          "Write a short paragraph and count how often each letter appears.",
          "Which letters appear most often? (E, T, A are most common in English)",
          "Try to decode: 'IFMMP XPSME' knowing each letter is shifted by one.",
          "Can you crack it?",
        ],
        w: "Frequency analysis is how code-breakers cracked historical ciphers. Human language has predictable statistical patterns — and that's what makes simple ciphers breakable.",
      },
    ],
    books: [
      { t: "Spy", a: "By Richard Platt", d: "A visual guide to espionage tools, codes, disguises, and spy techniques throughout history.", ag: "Ages 9–12" },
      { t: "Crime and Detection", a: "By Brian Lane", d: "Introduces kids to the science behind solving crimes — fingerprinting, surveillance, forensic evidence.", ag: "Ages 9–12" },
      { t: "One Dead Spy", a: "By Nathan Hale", d: "A graphic novel about Revolutionary War spy Nathan Hale — witty and packed with real espionage history.", ag: "Ages 8–11" },
    ],
  },
  {
    id: 11,
    slug: "herstory",
    name: "HerStory",
    icon: "⭐",
    ibg: "#FBEAF0",
    tc: "#993556",
    tbg: "#FBEAF0",
    stem: "History of STEM & Women in Science",
    subj: "Biology",
    type: "Card",
    age: "8-12",
    time: "30–60 min",
    players: "2–4",
    bgg: 369436,
    wiki: "HerStory_(card_game)",
    desc: "Celebrate real women who changed STEM — from Marie Curie to Mae Jemison — through discovery and play.",
    detail:
      "HerStory connects players to real women who transformed science, math, and exploration. Ada Lovelace wrote the world's first algorithm. Katherine Johnson calculated Apollo 11's trajectory. Marie Curie won Nobel Prizes in two different sciences. The game shows that STEM has always been shaped by brilliant people from all backgrounds.",
    concepts: [
      "History of Science",
      "Computer Science",
      "Mathematics",
      "Physics",
      "Chemistry",
      "STEM Careers",
      "Women in Science",
    ],
    roles: [
      { n: "Mathematician", d: "Uses numbers and logic to solve complex real-world problems." },
      { n: "Physicist", d: "Studies matter, energy, and the laws governing the universe." },
      { n: "Computer Scientist", d: "Designs algorithms and programs that power modern technology." },
      { n: "Astronaut", d: "Trains in science and engineering to conduct research in space." },
    ],
    facts: [
      "Marie Curie discovered two elements — polonium and radium — and won two Nobel Prizes.",
      "Ada Lovelace wrote what historians consider the world's first computer algorithm in the 1840s.",
      "Mae Jemison became the first Black woman in space aboard Shuttle Endeavour in 1992.",
      "Katherine Johnson's handwritten calculations helped NASA send John Glenn safely into orbit.",
      "Rosalind Franklin's X-ray images directly revealed DNA's double helix structure.",
      "Hedy Lamarr invented spread-spectrum radio technology that modern WiFi is based on.",
    ],
    tools: [
      "X-ray crystallography reveals the 3D structure of molecules by analyzing how X-rays scatter.",
      "Computer algorithms are step-by-step instructions that solve problems — pioneered by Ada Lovelace.",
      "Orbital trajectory calculation predicts exactly where a spacecraft must go to reach its target.",
      "Radioactivity research studies how unstable atoms release energy with medical and energy applications.",
      "Binary code represents all computer information as patterns of 0s and 1s.",
      "Spread-spectrum radio transmits signals across multiple frequencies to avoid interference.",
    ],
    exps: [
      {
        t: "Binary Bracelet (Ada Lovelace)",
        s: [
          "Choose a short word (like your name or STEM).",
          "Look up each letter's binary code using an ASCII chart.",
          "Pick two bead colors: one for 1, one for 0.",
          "String beads in the correct binary order and wear it!",
        ],
        w: "You're wearing the exact language every computer uses. Every photo, song, and video on the internet is stored as binary — the system Ada Lovelace helped pioneer.",
      },
      {
        t: "Paper Airplane Trajectories (Katherine Johnson)",
        s: [
          "Fold three different paper airplane designs.",
          "Launch each from the same point at the same angle.",
          "Measure and record how far each travels.",
          "Graph your results. Which design is most aerodynamic?",
        ],
        w: "Katherine Johnson used calculus and physics to calculate rocket trajectories. You're doing the same thing — measuring how design variables affect distance and flight path.",
      },
    ],
    books: [
      { t: "Hidden Figures (Young Readers' Edition)", a: "By Margot Lee Shetterly", d: "The true story of the Black women mathematicians at NASA whose calculations launched rockets into space.", ag: "Ages 9–13" },
      { t: "A Computer Called Katherine", a: "By Suzanne Slade", d: "Introduces young readers to Katherine Johnson, the trailblazing NASA mathematician.", ag: "Ages 7–10" },
      { t: "I Am Marie Curie", a: "By Brad Meltzer", d: "The story of the first woman to win a Nobel Prize — in two different sciences.", ag: "Ages 6–9" },
    ],
  },
  {
    id: 12,
    slug: "deep-dive",
    name: "Deep Dive",
    icon: "🐧",
    ibg: "#E6F1FB",
    tc: "#185FA5",
    tbg: "#E6F1FB",
    stem: "Marine Biology & Ocean Science",
    subj: "Biology",
    type: "Strategy",
    age: "5-8",
    time: "20–30 min",
    players: "1–4",
    bgg: 376747,
    wiki: "Deep_Dive_(board_game)",
    desc: "Dive with penguins into ocean zones and discover how animals adapt to life at extreme depths.",
    detail:
      "Deep Dive mirrors real ocean science. Emperor penguins dive over 1,500 feet and stay underwater for 20 minutes. The game explores ocean zones, bioluminescence, food webs starting with plankton, and the engineering challenges of deep-sea exploration with ROVs. Every zone in the game is a real scientific classification.",
    concepts: [
      "Ocean Zones",
      "Marine Adaptations",
      "Bioluminescence",
      "Buoyancy",
      "Food Webs",
      "Predator-Prey",
      "Pressure",
    ],
    roles: [
      { n: "Marine Biologist", d: "Studies ocean animals — their adaptations, behavior, and ecosystems." },
      { n: "Oceanographer", d: "Examines the physical and chemical properties of the ocean at all depths." },
      { n: "Deep-Sea Engineer", d: "Designs submersibles and ROVs that withstand crushing deep-sea pressure." },
      { n: "Conservation Scientist", d: "Works to protect ocean ecosystems from pollution and climate change." },
    ],
    facts: [
      "Emperor penguins can dive over 1,500 feet — deeper than most submarines go!",
      "The ocean has 5 zones: sunlight, twilight, midnight, abyssal, and hadal.",
      "Deep-sea animals use bioluminescence because no sunlight reaches below 1,000 feet.",
      "Water pressure at the deepest ocean point is over 1,000 times surface pressure.",
      "Marine food chains begin with phytoplankton — tiny organisms producing half Earth's oxygen.",
      "Scientists estimate 80% of the ocean remains unmapped and unexplored.",
    ],
    tools: [
      "ROVs explore the deep sea with cameras, robotic arms, and sensors.",
      "Pressure-resistant submersibles are built from titanium and special glass.",
      "Sonar mapping creates detailed pictures of the ocean floor using sound waves.",
      "Bioluminescence research reveals deep-sea communication and predation strategies.",
      "Water sampling at different depths reveals how temperature and oxygen change.",
      "Satellite tagging lets scientists track penguin diving patterns across entire seasons.",
    ],
    exps: [
      {
        t: "Ocean Zone Jar",
        s: [
          "Gather corn syrup (dark), dish soap, water with food coloring, and vegetable oil.",
          "Pour each liquid SLOWLY into a tall clear jar in order.",
          "Label layers: syrup=abyss, soap=midnight, water=twilight, oil=sunlight.",
          "Drop small objects in — which layer does each sink to?",
        ],
        w: "This models how water density changes with ocean depth. Cold, salty, deeper water is denser. Different animals are adapted to their specific pressure and temperature zone.",
      },
      {
        t: "Bioluminescence Art",
        s: [
          "Gather black paper and glow-in-the-dark paint or gel pens.",
          "Draw anglerfish, jellyfish, or squid with glowing patterns.",
          "Charge under a bright lamp for 60 seconds.",
          "View in a dark room. Where does the glow appear?",
        ],
        w: "Deep-sea animals have light-producing organs called photophores. They use light to attract prey, communicate, camouflage, and find mates — all in total darkness.",
      },
    ],
    books: [
      { t: "Penguins", a: "By Valerie Bodden", d: "Introduces young readers to penguin habitats, social behavior, and parenting.", ag: "Ages 6–9" },
      { t: "Alien Deep: Revealing the Mysterious Living World at the Bottom of the Ocean", a: "By Bradley Hague", d: "Explores hydrothermal vents and deep-sea creatures with real scientists.", ag: "Ages 9–12" },
      { t: "Penguins", a: "By Rachael Hanel", d: "Fun facts about how penguins hunt, move, and survive predators in the wild.", ag: "Ages 7–10" },
    ],
  },
  {
    id: 13,
    slug: "reef",
    name: "Reef",
    icon: "🪸",
    ibg: "#EAF3DE",
    tc: "#3B6D11",
    tbg: "#EAF3DE",
    stem: "Marine Biology & Environmental Science",
    subj: "Biology",
    type: "Strategy",
    age: "5-8",
    time: "30–45 min",
    players: "2–4",
    bgg: 244228,
    wiki: "Reef_(board_game)",
    desc: "Grow a coral reef and discover the real marine ecosystems that support 25% of all ocean species.",
    detail:
      "Reef models how coral grows layer by layer over thousands of years, responding to water temperature, chemistry, and surrounding organisms. It teaches ocean pH sensitivity, how currents distribute nutrients, and natural geometric patterns in coral structures. It powerfully highlights that coral reefs — built over millennia — are being damaged in decades.",
    concepts: [
      "Coral Ecosystems",
      "Ocean Chemistry",
      "pH & Acidification",
      "Patterns in Nature",
      "Conservation",
      "Climate Change",
      "Symbiosis",
    ],
    roles: [
      { n: "Marine Ecologist", d: "Studies relationships between coral, fish, algae, and reef organisms." },
      { n: "Ocean Chemist", d: "Analyzes how water chemistry — pH, temperature — affects marine life." },
      { n: "Conservation Biologist", d: "Develops strategies to protect and restore damaged coral reef ecosystems." },
      { n: "Climate Scientist", d: "Models how rising temperatures and acidification affect reefs globally." },
    ],
    facts: [
      "Coral reefs cover less than 1% of the ocean floor but support over 25% of all marine species.",
      "A living coral polyp is transparent — the color comes from algae living inside it.",
      "When oceans warm, coral expels its algae and turns white — this is called bleaching.",
      "The Great Barrier Reef is the largest living structure on Earth, visible from space.",
      "Coral reefs protect coastlines by absorbing up to 97% of wave energy during storms.",
      "Scientists grow coral in labs and transplant it onto damaged reefs to help them recover.",
    ],
    tools: [
      "Ocean pH monitoring tracks how CO₂ is making seas more acidic and damaging coral.",
      "Coral fragment transplanting grows new colonies from healthy reef sections.",
      "Water temperature sensors detect bleaching events before visible damage appears.",
      "Underwater photography documents reef health and species diversity over time.",
      "Genetic banking preserves coral DNA to protect diversity for future restoration.",
      "Computer modeling predicts which reefs are most resilient to climate change.",
    ],
    exps: [
      {
        t: "Coral Color Chemistry",
        s: [
          "Add 2 tablespoons of baking soda and food coloring to a small cup.",
          "Slowly pour in white vinegar.",
          "Watch the fizzing reaction — it represents how ocean acids react with coral.",
          "Try different amounts of vinegar. More acid = more fizzing = more damage.",
        ],
        w: "Ocean acidification works exactly like this — CO₂ dissolves in seawater forming carbonic acid, which dissolves the calcium carbonate that coral polyps use to build their skeletons.",
      },
      {
        t: "Ocean Current Experiment",
        s: [
          "Fill a clear container with water and let it become still.",
          "Drop food coloring in one corner.",
          "Very gently stir from one side only.",
          "Observe how the color spreads through the water.",
        ],
        w: "This models ocean currents distributing nutrients, oxygen, and plankton — the same currents that bring food to coral reefs and carry larvae to help reefs spread and recover.",
      },
    ],
    books: [
      { t: "Coral Reefs", a: "By Kristin Baird Rattini", d: "A colorful National Geographic overview of how coral reefs form, why they matter, and what lives within them.", ag: "Ages 7–10" },
      { t: "Alien Deep", a: "By Bradley Hague", d: "Explores uncharted ocean depths with real scientists — vents, deep-sea creatures, and mysteries.", ag: "Ages 9–12" },
      { t: "Fish", a: "By Steve Parker", d: "Introduces fish species, behaviors, and their roles in marine ecosystems.", ag: "Ages 8–12" },
    ],
  },
  {
    id: 14,
    slug: "world-wonders",
    name: "World Wonders",
    icon: "🏛",
    ibg: "#FAEEDA",
    tc: "#BA7517",
    tbg: "#FAEEDA",
    stem: "Ancient Engineering & Geography",
    subj: "Engineering",
    type: "Strategy",
    age: "8-12",
    time: "45–75 min",
    players: "2–5",
    bgg: 365258,
    wiki: "World_Wonders_(board_game)",
    desc: "Build legendary landmarks and discover the engineering, geometry, and physics behind history's greatest structures.",
    detail:
      "World Wonders explores incredible engineering achievements of ancient civilizations. The Great Pyramid aligns to true north with 0.05° accuracy using only observation. Machu Picchu used earthquake-resistant stonework. The Colosseum held 50,000 spectators with retractable awnings. Each wonder reflects deep scientific knowledge built without modern tools.",
    concepts: [
      "Civil Engineering",
      "Geometry",
      "Ancient Architecture",
      "Sustainability",
      "Load-Bearing Design",
      "Materials Science",
      "Cultural History",
    ],
    roles: [
      { n: "Archaeologist", d: "Excavates and studies physical remains of past civilizations and structures." },
      { n: "Civil Engineer", d: "Designs structures that safely support weight and withstand environmental forces." },
      { n: "Architectural Historian", d: "Studies how and why ancient buildings were designed as they were." },
      { n: "Materials Scientist", d: "Tests ancient materials like limestone and granite to understand their durability." },
    ],
    facts: [
      "The Great Pyramid aligns to true north with an accuracy of 0.05 degrees — built only with observation.",
      "Machu Picchu's interlocking stones required no mortar and survive earthquakes today.",
      "The Great Wall of China stretches over 13,000 miles across mountains and desert.",
      "Petra in Jordan was carved directly into rose-red sandstone cliffs using only hand tools.",
      "The Colosseum could fill 50,000 spectators through 80 entrance arches in minutes.",
      "Stonehenge's largest stones weighed up to 25 tons and were transported 25 miles.",
    ],
    tools: [
      "Structural load analysis calculates how weight distributes through arches, columns, foundations.",
      "Geometric surveying uses angles and proportions to align structures with astronomical precision.",
      "Simple machines — levers, ramps, pulleys, wheels — moved massive stone blocks.",
      "Mortar analysis examines ancient binding agents and their surprising durability.",
      "Ground-penetrating radar finds buried foundations beneath ancient sites.",
      "3D scanning creates exact digital models of ancient structures for preservation and study.",
    ],
    exps: [
      {
        t: "Paper Bridge Engineering",
        s: [
          "Use only one sheet of paper and tape to span a 15cm gap between two books.",
          "Test how many pennies your bridge holds before collapsing.",
          "Try again with different folds: accordion, tube, arch shapes.",
          "Which design holds the most weight?",
        ],
        w: "Ancient bridge and arch builders solved the same problem. Arch shapes redirect compression forces to the sides — exactly as Roman aqueducts did 2,000 years ago.",
      },
      {
        t: "Pyramid Geometry Challenge",
        s: [
          "Cut 4 equal triangles from cardboard.",
          "Tape them together to form a pyramid with an open square base.",
          "Measure the base and slant height.",
          "Does the 4:1 base-to-height ratio match the Great Pyramid's proportions?",
        ],
        w: "The Great Pyramid's architects embedded precise geometric ratios into the structure's very dimensions — mathematical constants visible in its proportions to this day.",
      },
    ],
    books: [
      { t: "Grand Canyon", a: "By Jason Chin", d: "A stunning illustrated look at the geologic history and breathtaking scale of this natural wonder.", ag: "Ages 8–12" },
      { t: "Where Is the Great Barrier Reef?", a: "By Nico Medina", d: "Introduces the biodiversity and ecological importance of the Great Barrier Reef.", ag: "Ages 8–11" },
      { t: "Eyewitness: National Parks", a: "By Andrea Mills", d: "Highlights the beauty, diversity, and conservation efforts behind the world's national parks.", ag: "Ages 9–12" },
    ],
  },
  {
    id: 15,
    slug: "tokyo-highway",
    name: "Tokyo Highway",
    icon: "🌆",
    ibg: "#E1F5EE",
    tc: "#0F6E56",
    tbg: "#E1F5EE",
    stem: "Physics & Urban Engineering",
    subj: "Engineering",
    type: "Dexterity",
    age: "8-12",
    time: "20–40 min",
    players: "2–4",
    bgg: 215463,
    wiki: "Tokyo_Highway_(board_game)",
    desc: "Balance elevated highway networks and discover the real physics of structural engineering and urban planning.",
    detail:
      "Tokyo Highway teaches real structural engineering through play. Tension, compression, and gravity all affect how elevated roads stay up — exactly the forces engineers calculate for real highways. Japan's roads must withstand earthquakes using special damping systems. The game also explores center of mass, spatial reasoning, and dense urban planning challenges.",
    concepts: [
      "Structural Engineering",
      "Forces: Tension & Compression",
      "Urban Planning",
      "Center of Mass",
      "Spatial Reasoning",
      "Earthquake Engineering",
      "Balance",
    ],
    roles: [
      { n: "Structural Engineer", d: "Designs roads, bridges, and elevated highways that safely carry loads." },
      { n: "Urban Planner", d: "Decides where roads, buildings, parks, and transit go in a city." },
      { n: "Seismic Engineer", d: "Designs structures in earthquake zones to flex and absorb ground motion." },
      { n: "Transportation Engineer", d: "Optimizes traffic flow, ramp design, and intersection safety." },
    ],
    facts: [
      "Tokyo has over 10,000 km of elevated roads — every design must account for earthquakes.",
      "Tension pulls (like suspension bridge cables). Compression pushes (like pillars under weight).",
      "Japan uses base isolators under buildings: rubber-steel cushions that absorb earthquake energy.",
      "The center of mass is the single point where all of an object's weight is perfectly balanced.",
      "Elevated highways save city space by stacking roads over existing streets and buildings.",
      "Some Tokyo highways were built threading directly through existing multi-story buildings!",
    ],
    tools: [
      "Finite element analysis uses computers to model how forces flow through complex structures.",
      "Wind tunnel testing shows how elevated roads respond to high winds and air turbulence.",
      "Seismic simulation shakers test whether bridge models survive earthquake forces.",
      "Center-of-mass calculation is essential for structures that won't topple under uneven loads.",
      "Traffic flow modeling uses math to optimize lanes, ramps, and interchanges.",
      "Material fatigue testing reveals how metals and concrete weaken over years of repeated stress.",
    ],
    exps: [
      {
        t: "Balance & Weight Distribution",
        s: [
          "Balance a ruler between two equal stacks of books.",
          "Place a coin directly in the center. Does it still balance?",
          "Move the coin to the left. What happens?",
          "Add coins to the other side to restore balance. Where do they need to go?",
        ],
        w: "You're demonstrating the lever principle and center of mass — the fundamental calculation every structural engineer makes when designing an elevated road or bridge.",
      },
      {
        t: "String Suspension Bridge",
        s: [
          "Tie two pieces of string between two chairs of equal height.",
          "Tape a cardboard strip across the middle as your 'roadway.'",
          "Hang a small cup from the center of the cardboard.",
          "Slowly add pennies. How many can the suspension system hold?",
        ],
        w: "Suspension bridges transfer weight through cables or pillars to the ground. The string in your bridge works like the cables of the Golden Gate or Tokyo's Rainbow Bridge.",
      },
    ],
    books: [
      { t: "City Atlas", a: "By Georgia Cherry", d: "A beautifully illustrated tour of cities around the world, including Tokyo — how cities are organized and how people travel.", ag: "Ages 8–11" },
      { t: "Japan", a: "By Marty Gitlin", d: "A comprehensive guide to Japanese culture, geography, and traditions — the real setting behind Tokyo Highway.", ag: "Ages 9–12" },
      { t: "Foods of Japan", a: "By Christine VeLure Roholt", d: "Japanese food customs, meals, and how culture shapes city life.", ag: "Ages 8–11" },
    ],
  },
];
